### ISSUE TITLE
sample for asp.net or asp.net core

### ISSUE THREAD

**Issue by allenhula** [Azure/azure-relay#24]
Any plan to provide sample for asp.net or asp.net core?

**Comment by npnelson** [comment]
ping @sethmanheim . Sorry for pinging you Seth, but as far as I can tell it looks like you work for Microsoft and have made recent contributions on GitHub in the Azure Service Bus area. I would really like to use Azure Hybrid Relay (especially something like PortBridge on .NET Core). It looks like these samples and the relay client itself https://github.com/Azure/azure-relay-dotnet haven't seen any activity in almost a year. 

Is Microsoft going to dedicate any resources to keeping this up to date (i.e. .Net Standard/Core 2.0)? The portbridge sample in particular needs a decent overhaul for .NET Core 2.0 (i.e. use Microsoft.Extensions.Configuration instead of app.config, Microsoft.Extensions.Logging instead of Trace, get rid of IAsyncResult to name a few)

If you aren't the right person to ask, can you forward to the right person?

**Comment by sethmanheim** [comment]
Adding the PM for relay, @JustinConway. He would have to answer these questions.

**Comment by npnelson** [comment]
@JustinConway appears to be missing in action. It's unfortunate that no one is owning the issues here or at https://github.com/Azure/azure-relay-dotnet. I haven't seen any activity from a contributor in that one since July 2017. Even Microsoft employees can't get answers on the Azure Relay repo https://github.com/Azure/azure-relay-dotnet/issues/60

I would like to use Azure Relay, but the fact that the last release of the SDK was almost a year ago and that numerous issues in the relay repos go unanswered makes me question Microsoft's commitment to the product. 

The service bus team does a good job with their repo https://github.com/Azure/azure-service-bus-dotnet, maybe they can help out?

Sorry for the public trolling, but I couldn't even figure out how to effectively contact anyone privately about these concerns.

**Comment by JustinConway** [comment]
@npnelson I'm here and Azure Relay is still fully supported:) We actually really appreciate you being vocal on this. We have been doing some work internally to figure out the direction we want to take Azure Relay and then properly invest in a roadmap that will benefit new and current customers. We'll have some big announcements with the service this year, but in the meantime I will see what we can do to make some updates to samples and respond where we can.

**Comment by npnelson** [comment]
@JustinConway Thanks for the update! For me, Azure Relay has huge potential in allowing me to support software (running on .NET Core Linux) running behind my customers' firewalls. I am on a crusade to kill the use of private network connections and VPNs in my organization because they are costly and overly complicated and fragile. Relay (or something like it) is a key piece for me to accomplish that. Feel free to reach out to me if discussing my use case helps you with your plans.

**Comment by jfggdl** [comment]
For completeness and before closing this issue, the ASP.NET samples were released on May 2018 and you can find them here: https://github.com/Azure/azure-relay/tree/master/samples/hybrid-connections/dotnet/aspnet.
